# Generated by Django 6.0.2 on 2026-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_refund_amount_booking_refund_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='issue_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
