# Generated by Django 6.0.6 on 2026-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_dispute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispute',
        ),
    ]
