# Generated by Django 6.0.2 on 2026-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorkyc',
            name='document_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendorkyc',
            name='document_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
