# Generated by Django 6.0.6 on 2026-06-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorkyc_document_type_vendorkyc_document_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorKYC',
        ),
    ]
