# Generated by Django 6.0.6 on 2026-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_delete_vendorkyc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorDispute',
        ),
    ]
