# Generated by Django 6.0.2 on 2026-03-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_reviewcomment'),
    ]

    operations = [
    ]
