# Generated by Django 6.0.2 on 2026-03-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_reviewcomment'),
        ('subscriptions', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='subscriptions.vendorsubscription'),
        ),
    ]
