# Generated by Django 6.0.6 on 2026-06-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_vendor_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='kyc_status',
        ),
    ]
