# Generated by Django 6.0.6 on 2026-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_vendor_kyc_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
