# Generated by Django 6.0.6 on 2026-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout_vendorbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbankaccount',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.DeleteModel(
            name='VendorBankAccount',
        ),
    ]
